### ISSUE TITLE
turn purple selection to grey

### ISSUE THREAD

**Issue by fg75** [moka-project/orchis-gtk-theme#73]
I've found using "purple" color for the selection items very odd. It has very poor constrast for black text. Go into /usr/share/themes/Orchis folder and launch

sudo find ./ -type f | xargs sudo sed -i 's/A348B1/AAAAAA/g'

this will turn purple into med-light gray. Substitute AAAAAA with the hex code
for the color you like.

Best,

F

**Comment by snwh** [comment]
Not happening.
