### ISSUE TITLE
Libreoffice 4.4.2.2 font and style selector not clearing previous selection

### ISSUE THREAD

**Issue by Cykc44** [moka-project/orchis-gtk-theme#78]
Hi

I'm on Ubuntu 14.04 with Orchis installed via ppa. Under Libreoffice  4.4.2.2 Writer and Calc there is a small glitch where when you change font or  text style the previous selection remains underneath the new choice, the background colour also remains.

![screenshot from 2015-05-01 14 24 49](https://cloud.githubusercontent.com/assets/10181125/7430750/1f9f14ec-f00f-11e4-8f10-2be68d575627.png)

Many thanks
for all the hard work

**Comment by leoheck** [comment]
It seems to be fixed on v4.4.3.2

![screenshot from 2015-05-21 21 02 36](https://cloud.githubusercontent.com/assets/1277920/7761483/bbe46f26-fffc-11e4-9a66-cbd3bf122fa1.png)

**Comment by Cykc44** [comment]
Brilliant thanks for that

**Comment by choclo45** [comment]
I had similar problem in Mint 17.2 (xfce). It's appearance theme problem. Using default or other themes you can find solution.

**Comment by leoheck** [comment]
Maybe, I use it with [orchis](https://github.com/moka-project/orchis-gtk-theme) theme. I'm also using Libreoffice 5.0 right now and it looks very good.
